run:
  # Timeout for analysis
  timeout: 5m
  
  # Skip test files
  skip-files:
    - ".*_test\\.go$"

linters:
  enable-all: false
  disable-all: false

issues:
  # Exclude test files from all linters
  exclude-rules:
    - path: _test\.go
      linters:
        - all

