version: '3'

vars:
  DB_USER: '{{.DB_USER | default "postgres"}}'
  DB_PASSWORD: '{{.DB_PASSWORD | default "password"}}'
  DB_NAME: '{{.DB_NAME | default "articles"}}'
  DB_PORT: '{{.DB_PORT | default "5432"}}'
  VERSION: '{{.VERSION}}'
  DOCKER_IMAGE_NAME: "antohachaban/articles-go:{{.VERSION}}"

tasks:
  build:
    cmds:
      - docker build . -f ./Dockerfile -t {{.DOCKER_IMAGE_NAME}}
    desc: "Build the Docker image"

  run-docker:
    cmds:
      - docker run -d -p {{.PORT}}:8080 --name articles-go-container {{.DOCKER_IMAGE_NAME}}
    vars:
      PORT: '{{default "8080" .PORT}}'
    desc: "Run the Docker container, example: task build PORT=8080"

  push-docker:
    cmds:
      - docker push {{.DOCKER_IMAGE_NAME}}
    desc: Push the Docker image to the registry

  format:
    cmds:
      - go fmt ./...
    desc: Format the code

  vet:
    cmds:
      - go vet ./...
    desc: Run go vet to check for issues

  tidy:
    cmds:
      - go mod tidy
    desc: Run go mod tidy to clean up dependencies

  build-go:
    cmds:
      - go build -o web.exe ./cmd/server
    desc: Build the Go source code

  test:
    cmds:
      - go test ./...
    desc: Run all tests

  run-postgres:
    cmds:
      - docker run --name postgres-db -p {{.DB_PORT}}:5432 -e POSTGRES_USER={{.DB_USER}} -e POSTGRES_PASSWORD={{.DB_PASSWORD}} -e POSTGRES_DB={{.DB_NAME}} -d postgres
    desc: Run PostgreSQL in Docker container

  all-checks:
    desc: Run format, vet, lint
    cmds:
      - task format
      - task vet
      - task tidy

  helm-install:
    desc: "Install the Helm chart"
    dir: helm
    cmds:
      - helm upgrade --install articles-release . -f values.yaml

  helm-delete:
    desc: "Delete the Helm release"
    cmds:
      - helm delete articles-release

  helm-package:
    desc: "Package the Helm chart"
    dir: helm
    cmds:
      - helm package .